server:
  port: 8000
  
spring:
  application:
    name: manage-company-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/manage_company
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  
#logging:
#  file:
#    name: C:/stock-market-logs/manage-company-service/company_service_logs.log
   
management:
  endpoints:
    web:
      exposure:
        include: '*'
